### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by surgiie** [gregedmonds/tcgmerch#2]
Need to identify layouts for each of the breakpoints (LG,MD,SM)

**Comment by gregedmonds** [comment]
That is your job, silly.

**Comment by surgiie** [comment]
@gregedmonds 

For this project, its our job. Good practice for bootstrap :)

**Comment by gregedmonds** [comment]
Yeah, yeah, yeah.  I just like to type in this box.

**Comment by surgiie** [comment]
@gregedmonds get charlie in here lol then we can have some real fun. 👍
